### ISSUE TITLE
ColonyScanalyser 0.5.0 crashes on input previous version worked on

### ISSUE THREAD

**Issue by vladimirg** [Erik-White/ScanLag#62]
Input data is on Dropbox: `Berman Lab Staff Files/Alona/Scanner0`

```
(base) bermanlab@britanya418-1:~/Documents/scanalyser_test$ scanalyser Scanner0/ -v 
Starting ColonyScanalyser analysis
Multiprocessing enabled, utilising 7 of 8 processors
Working directory: /Users/bermanlab/Documents/scanalyser_test/Scanner0
100 images found
Preprocessing images to locate plates
Traceback (most recent call last):
  File "/opt/anaconda3/bin/scanalyser", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.7/site-packages/colonyscanalyser/main.py", line 292, in main
    with image_files.items[0] as image_file:
  File "/opt/anaconda3/lib/python3.7/site-packages/colonyscanalyser/image_file.py", line 42, in __enter__
    self._image = ImageFile._load_image(self.file_path)
  File "/opt/anaconda3/lib/python3.7/site-packages/colonyscanalyser/image_file.py", line 125, in _load_image
    return image_as_rgb(imread(str(file_path), as_gray = as_gray, plugin = plugin, **plugin_args))
  File "/opt/anaconda3/lib/python3.7/site-packages/colonyscanalyser/imaging.py", line 257, in image_as_rgb
    return rgba2rgb(image)
  File "/opt/anaconda3/lib/python3.7/site-packages/skimage/color/colorconv.py", line 193, in rgba2rgb
    raise ValueError(msg)
ValueError: the input array must have shape == (..., 4)), got (3510, 2550, 3)
```

**Comment by Erik-White** [comment]
Oops, I overlooked the obvious case where an image is already RGB and doesn't need conversion!
